import os, sys, time, re, pickle

from optparse import OptionParser

from scripts.EMBL.projects.lamin_analysis import FeatureProjectionAnalysis

if __name__ ==  "__main__":

    description =\
'''
%prog - generation of single cell html pages.
Prerequesites are gallery images (generated by scripts.cutter.cut_tracks_from_resultfile.py ) ,
a settings file for the whole workflow (like scripts/EMBL/settings_files/lamin/settings_lamin_analysis.py)
and the generated single cell plots. The scripts just links existing information together.
'''

    parser = OptionParser(usage="usage: %prog [options]",
                          description=description)

    parser.add_option("-s", "--settings_files", dest="settings_file",
                      help="Filename of the settings file for the postprocessing")
    parser.add_option("--plot_generation", action="store_true", dest="plot_generation",
                      help="Filename of the settings file for the postprocessing")

    (options, args) = parser.parse_args()

    if (options.settings_file is None):
        parser.error("incorrect number of arguments!")

    plot_generation = options.plot_generation
    if plot_generation is None:
        plot_generation = False

    fpa = FeatureProjectionAnalysis(options.settings_file)

    # plot generation
    if plot_generation:
        fpa.batchPlotGeneration()

    # make HTML pages
    fpa.makeHTMLDataForPlate()

