#!/bin/bash
#
# 04/02/2013 Rudolf Hoefler
#

RCFILE=cellcognition_debian7

if [ -r /etc/profile.d/modules.sh ]; then
    . /etc/profile.d/modules.sh
fi

if [ -r ~cecog/.bashrc ]; then
    . ~cecog/.bashrc
fi

if [ -r $HOME/gateway/$RCFILE ]; then
    . $HOME/gateway/$RCFILE
    echo "configuration from $HOME/$RCFILE"
elif [ -r /etc/defaults/$RCFILE ]; then
    . /etc/default/$RCFILE
    echo "configuration from /etc/defaults/$RCFILE"
else
    echo "No gateway configuration found!"
    exit 1
fi

# start
start() {
    echo "Starting gateway"
    echo $CMD
    mkdir -p ${LOG_DIR}
    /sbin/start-stop-daemon --start --pidfile ${PIDFILE} \
        --user ${C_USER} --group ${C_GROUP} \
        -b --make-pidfile \
	--umask ${C_UMASK} \
        --chuid ${C_USER} \
        --exec ${CMD} -- $GATEWAYOPTS
}

# stop
stop() {
    echo "Stopping gateway"
    /sbin/start-stop-daemon --stop --pidfile ${PIDFILE} --verbose
    if [ $? -eq 0 ]; then
        rm -f ${PIDFILE}
    fi
}


# do it
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
esac
