#!/bin/bash
#
# 04/02/2013 Rudolf Hoefler
#

#---------------------------------------------------------------------------
# The following lines provide the necessary info for adding a startup script
# according to the Linux Standard Base Specification (LSB) which can
# be found at:
#
#    http://www.linuxfoundation.org/spec/booksets/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html
#
### BEGIN INIT INFO
# Provides:       cecog-gateway
# Required-Start: $network $remote_fs
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Description:  start Cellcognition gateway
### END INIT INFO
#---------------------------------------------------------------------------

RCFILE=cellcognition.haring

if [ -r /etc/profile.d/modules.sh ]; then
    . /etc/profile.d/modules.sh
fi

if [ -r ~cecog/.bashrc ]; then
    . ~cecog/.bashrc
fi

if [ -r /home/imba/cecog/gateway/$RCFILE ]; then
    . /home/imba/cecog/gateway/$RCFILE
    echo "configuration from /home/imba/cecog/gateway/$RCFILE"
elif [ -r /etc/defaults/$RCFILE ]; then
    . /etc/default/$RCFILE
    echo "configuration from /etc/defaults/$RCFILE"
else
    echo "No gateway configuration found!"
    exit 1
fi

start() {
    echo "Starting gateway"
    echo $CMD
    mkdir -p ${LOG_DIR}
    /sbin/start-stop-daemon --start --pidfile ${PIDFILE} \
        --user ${C_USER} --group ${C_GROUP} \
        -b --make-pidfile \
	--umask ${C_UMASK} \
        --chuid ${C_USER} \
        --exec ${CMD} -- $GATEWAYOPTS
}

stop() {
    echo "Stopping gateway"
    /sbin/start-stop-daemon --stop --pidfile ${PIDFILE} --verbose
    if [ $? -eq 0 ]; then
        rm -f ${PIDFILE}
    fi
}


# do it
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
esac
