#!/bin/bash -l

# Defaults for cecog-gateway
# sourced by /etc/init.d/cecog-gateway
# installed at /etc/default/cellcognition by the maintainer scripts
#
# Gateway setup for the cellcognition cluster environment

# move this to .bashrc after migration
module load gridengine
export PYTHONPATH=$PYTHONPATH:$HOME/sandbox/cellcognition/pysrc
export CECOG_VERSIONS=$HOME/cecog_versions
export JOB_PARAMS="-m bea -q public.q -P CellCognition"

CECOG_GATEWAY_HOME=$HOME/gateway
LOG_DIR=$CECOG_GATEWAY_HOME
LOGFILE=$LOG_DIR/gateway.log

C_HOST=login-debian7.bioinfo.imp.ac.at
C_PORT=9999
# u=rwx,g=rwx,o=r
C_UMASK=002
C_USER=cecog
C_GROUP=Gerlich.GRP

# PYTHONP_BIN should be exported by .profile
export PYTHON_BIN=$(which python)
GATEWAY_PY="$HOME/gateway/gateway.py"
CMD="$PYTHON_BIN $GATEWAY_PY"
GATEWAYOPTS="--host=$C_HOST --port=$C_PORT >$LOGFILE 2>$LOGFILE"

PIDFILE=${LOG_DIR}/gateway.pid
